name: Trivy Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '15 8 * * 5'

permissions:
  contents: read

jobs:
  trivy-scan:
    name: Run Trivy Vulnerability Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Clean up disk space before build
      - name: Clean up Docker environment
        run: |
          docker system prune -af --volumes || true
          sudo rm -rf /var/lib/docker/tmp/* || true

      # Define image name as a consistent variable
      - name: Set up image name
        id: vars
        run: echo "IMAGE_NAME=my-app:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          echo "Building Docker image $IMAGE_NAME"
          docker build -t $IMAGE_NAME .

      - name: Verify image built successfully
        run: docker images

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
